### ISSUE TITLE
二维码合一

### ISSUE THREAD

**Issue by edwardtoday** [Sansi/StellarSite#2]
1. 蓝牙灯没卖，去掉。
1. Stellar Wi-Fi的app二维码，两个平台的合一。

参考

- http://onelink.to/
- http://stackoverflow.com/questions/6531667/how-to-make-qr-code-for-both-android-market-and-app-store
- http://omniqrcode.com/
- https://manage.appurl.io/

**Comment by zqtqzy** [comment]
已完成
